name: CI
env:
  GITHUB_TOKEN: ${{ secrets.TOT }}
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
         sudo apt install -y ffmpeg
      - run: |
         ffmpeg -i audio/4.mp3 audio/test.wav
         ./rhubarb -r phonetic -o output.txt audio/test.wav
         awk 'NR!=1 {print int(($1*24)-1)}' output.txt > output2.txt
         awk 'END{print int($1*24)}' output.txt >> output2.txt
         awk 'NR==FNR{a[NR]=$0;next}{print a [FNR],$0}' output2.txt output.txt > output3.txt
         awk '{print "for ((i="int($2*24)"; i<="$1"; i++)); do convert lisa-"$3".png output_$(printf %05d $i).png ; done"}' output3.txt > output.sh
         chmod +x output.sh
         ./output.sh
         ffmpeg -framerate 24 -i output_%05d.png -vcodec png  output.mp4 -y
         ffmpeg -i output.mp4 -i audio/test.wav -map 1:0 -map 0:0 final.mp4 -y
         
      - name: Run a one-line script
        run: |
         git add final.mp4
         git add video/preview.mp4
         git config --global user.name 'Your Name'
         git config --global user.email 'your-username@users.noreply.github.com'
         git commit -am `date +%s`
         git push
