name: CI
env:
  GITHUB_TOKEN: ${{ secrets.TOT }}
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
         sudo apt install -y ffmpeg
         ffmpeg -i audio/3.mp3 audio/3.wav
         ./rhubarb -o output.txt audio/3.wav
         awk 'NR!=1 {print int(($1*24)-1)}' output.txt > output2.txt
         awk 'END{print int($1*24)}' output.txt >> output2.txt
         awk 'NR==FNR{a[NR]=$0;next}{print a [FNR],$0}' output2.txt output.txt > output3.txt
         awk '{print "for ((i="int($2*24)"; i<="$1"; i++)); do convert lisa-"$3".png output_$(printf %05d $i).png ; done"}' output3.txt > output.sh
         chmod +x output.sh
         ./output.sh
         ffmpeg -framerate 24 -i output_%05d.png -vcodec png  output.mov
        
         
      - name: Run a one-line script
        run: |
         date +%s > README.md
         git add output.mov
         git config --global user.name 'Your Name'
         git config --global user.email 'your-username@users.noreply.github.com'
         git commit -am "report"
         git push
