name: C/C++ CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
    # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: 3.10
    - run: pip install faster-whisper
    - run: ct2-transformers-converter --model cahya/whisper-medium-id --output_dir faster-whisper-medium-id --quantization float16
