name: test
on:
  push:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.8'  # Specify the Python version you need, e.g., '3.8'

    - name: Get Google Chrome version
      id: chrome-version
      run: echo "::set-output name=version::$(choco search googlechrome --exact --limit-output | Select-String -Pattern '^googlechrome ' | ForEach-Object { $_.Line.Split()[1] })"
      shell: pwsh

    - name: Cache Google Chrome
      id: cache-chrome
      uses: actions/cache@v3
      with:
        path: C:\Program Files\Google\Chrome\Application
        key: google-chrome-${{ steps.chrome-version.outputs.version }}

    - name: Install Google Chrome using Chocolatey
      if: steps.cache-chrome.outputs.cache-hit != 'true'
      run: choco install googlechrome -y

    - name: Cache pip packages
      id: cache-pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-cache-${{ runner.os }}-pyautogui
        restore-keys: |
          pip-cache-${{ runner.os }}-

    - name: Install pyautogui
      run: pip install pyautogui

    - name: run test
      run: |
        python main.py
        git add screenshot.png
        git config --global user.name 'Your Name'
        git config --global user.email 'your-username@users.noreply.github.com'
        git commit -am "Automated report"
        git push

