name: C/C++ CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
    - run: npm install axios
    - run: |
       echo "{" > config.json
       echo '  "YOUTUBE_API_KEY": "YOUR_YOUTUBE_API_KEY"' >> config.json
       echo "}" >> config.json
       cat config.json
    - run: ls
