name: test
on:
  push:
  schedule:
    - cron:  '* */1 * * *'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.8'  # Specify the Python version you need, e.g., '3.8'

    - name: Install pyautogui
      run: |
        pip install youtube_dl
        pip show youtube_dl
        python get_id.py
        dir "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages\youtube_dl\extractor"
    - name: run if puisi sama dengan g
      run: |
        git add videos.json
        git config --global user.name 'Your Name'
        git config --global user.email 'your-username@users.noreply.github.com'
        git commit -am "Automated report"
        git push
