name: Parallel Jobs Example

on: [push, pull_request]

jobs:
  generate-numbers:
    runs-on: ubuntu-latest
    outputs:
      numbers: ${{ steps.generate.outputs.numbers }}
    steps:
    - name: Generate Numbers
      id: generate
      run: |
        numbers=$(seq 1 10 | tr '\n' ' ')
        echo "numbers=$numbers" >> $GITHUB_ENV

  parallel-jobs:
    needs: generate-numbers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: ${{ env.numbers }}
    steps:
    - name: Run Parallel Job
      run: |
        echo "Running job for number: ${{ matrix.number }}"
