name: Parallel Jobs Example

on: [push, pull_request]

jobs:
  generate-numbers:
    runs-on: ubuntu-latest
    outputs:
      numbers: ${{ steps.generate.outputs.numbers }}
    steps:
    - name: Generate Numbers
      id: generate
      run: |
        numbers=$(seq 1 10 | jq -c -R 'split(" ") | map(tonumber)')
        echo "numbers=$numbers" >> $GITHUB_ENV
      env:
        GITHUB_ENV: $GITHUB_ENV

  parallel-jobs:
    needs: generate-numbers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: a${{ fromJson(needs.generate-numbers.outputs.numbers) }}
    steps:
    - name: Run Parallel Job
      run: |
        echo "Running job for number: ${{ matrix.number }}"
