name: Parallel Jobs Example

on: [push, pull_request]

jobs:
  parallel-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [1, 2, 3, 4, 5, 6,]
    steps:
    - name: Run Parallel Job
      run: |
        echo "Running job for number: ${{ matrix.number }}"
